### ISSUE TITLE
[VQ] visual querying page test

### ISSUE THREAD

**Issue by johannesliem** [InTaVia/web#64]
When running validation I get this message for the passing test of the visual querying page (on dev).

` PASS  test/pages/visual-querying.page.test.tsx (7.408 s)
  ● Console

    console.warn
      No constraint ring description defined for constraint type: undefined

      91 |           }
      92 |           default:
    > 93 |             console.warn(
         |                     ^
      94 |               'No constraint ring description defined for constraint type:',
      95 |               constraint.type,
      96 |             );

      at map (src/features/visual-querying/PersonShape.tsx:93:21)
          at Array.map (<anonymous>)
      at PersonShape (src/features/visual-querying/PersonShape.tsx:66:17)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)
      at updateFunctionComponent (node_modules/react-dom/cjs/react-dom.development.js:17356:20)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19063:16)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23940:14)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22779:12)`

**Comment by samuelbeck** [comment]
Solved in PR #65
