### ISSUE TITLE
Test TimelinePage: should how a tooltip on hover fails

### ISSUE THREAD

**Issue by samuelbeck** [InTaVia/web#66]
The mentioned test sometimes passes and sometimes fails with the following message:

```
● TimelinePage › should show a tooltip on hover

    expect(element).not.toBeInTheDocument()

    expected document not to contain element, found <div class="MuiTooltip-popper css-17gg73c-MuiPopper-root-MuiTooltip-popper" data-popper-escaped="" data-popper-placement="bottom" data-popper-reference-hidden="" id="mui-41" role="tooltip" style="position: absolute; left: 0px; top: 0px; margin: 0px; transform: translate(0px, 0px);"><div class="MuiTooltip-tooltip MuiTooltip-tooltipPlacementBottom css-ja5taz-MuiTooltip-tooltip" style="opacity: 0; transform: scale(0.75, 0.5625); transition: opacity 200ms cubic-bezier(0.4, 0, 0.2, 1) 0ms,transform 133ms cubic-bezier(0.4, 0, 0.2, 1) 67ms;"><div class="MuiBox-root css-0"><h5 class="MuiTypography-root MuiTypography-h5 css-ag7rrr-MuiTypography-root">Deborah Knoll V</h5><ul class="MuiTypography-root MuiTypography-body2 css-17k2v99-MuiTypography-root"><li class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root">born<span class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root"> in <span class="MuiTypography-root MuiTypography-body2 css-1d3njat-MuiTypography-root">Lavamünd</span></span><span 
class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root"> on <span class="MuiTypography-root MuiTypography-body2 css-1d3njat-MuiTypography-root">March  1, 1918</span></span></li><li class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root">died<span class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root"> in <span class="MuiTypography-root MuiTypography-body2 css-1d3njat-MuiTypography-root">Graz</span></span><span class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root"> on <span class="MuiTypography-root MuiTypography-body2 css-1d3njat-MuiTypography-root">February 21, 1936</span></span></li><li class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root">lived<span class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root"> in <span class="MuiTypography-root MuiTypography-body2 css-1d3njat-MuiTypography-root">Untertilliach</span></span><span class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root"> on <span class="MuiTypography-root MuiTypography-body2 css-1d3njat-MuiTypography-root">June 29, 1927</span></span></li><li class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root">stayed<span class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root"> in <span class="MuiTypography-root MuiTypography-body2 css-1d3njat-MuiTypography-root">Pitschgau</span></span><span class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root"> on <span class="MuiTypography-root MuiTypography-body2 css-1d3njat-MuiTypography-root">February  2, 1925</span></span></li><li class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root">stayed<span class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root"> in <span class="MuiTypography-root MuiTypography-body2 css-1d3njat-MuiTypography-root">Neukirchen an der Enknach</span></span><span class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root"> on <span class="MuiTypography-root MuiTypography-body2 css-1d3njat-MuiTypography-root">October 23, 1932</span></span></li><li class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root">statue erected<span class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root"> in <span class="MuiTypography-root MuiTypography-body2 css-1d3njat-MuiTypography-root">Arriach</span></span><span class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root"> on <span class="MuiTypography-root MuiTypography-body2 css-1d3njat-MuiTypography-root">January 28, 1950</span></span></li></ul><p class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root">Modi quo sapiente sunt repudiandae dolor maiores dolor. Non possimus provident perferendis tenetur dolores iure quia nemo neque. Enim neque aut ut voluptates ea molestias est. Sequi et in voluptatibus. Dolorem culpa minus tempora eaque. Eius quia dolorem deserunt voluptatem distinctio totam dolore occaecati debitis.</p></div></div></div> instead

    Ignored nodes: comments, <script />, <style />
    <html>
      <head />
      <body>
        <div>
          <div
            class="MuiContainer-root MuiContainer-maxWidthMd css-1h5qbo1-MuiContainer-root"
          >
            <header
              class="MuiBox-root css-1czkgpg"
            >
              <h1
                class="MuiTypography-root MuiTypography-h2 css-1sra7t5-MuiTypography-root"
              >
                Timeline
              </h1>
            </header>
            <div
              class="MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 css-1ps6pg7-MuiPaper-root"
            >
              <div
                class="MuiBox-root css-19midj6"
              >
                <label
                  class="MuiFormControlLabel-root MuiFormControlLabel-labelPlacementEnd css-j204z7-MuiFormControlLabel-root"
                >
                  <span
                    class="MuiSwitch-root MuiSwitch-sizeMedium css-julti5-MuiSwitch-root"
                  >
                    <span
                      class="MuiSwitch-switchBase MuiSwitch-colorPrimary Mui-checked MuiButtonBase-root MuiSwitch-switchBase MuiSwitch-colorPrimary Mui-checked PrivateSwitchBase-root Mui-checked css-5ryogn-MuiButtonBase-root-MuiSwitch-switchBase"
                    >
                      <input
                        checked=""
                        class="MuiSwitch-input PrivateSwitchBase-input css-1m9pwf3"
                        type="checkbox"
                      />
                      <span
                        class="MuiSwitch-thumb css-jsexje-MuiSwitch-thumb"
                      />
                      <span
                        class="MuiTouchRipple-root css-8je8zh-MuiTouchRipple-root"
                      />
                    </span>
                    <span
                      class="MuiSwitch-track css-1yjjitx-MuiSwitch-track"
                    />
                  </span>
                  <span
                    class="MuiTypography-root MuiTypography-body1 MuiFormControlLabel-label css-ahj2mt-MuiTypography-root"
                  >
                    Zoom to data time range
                  </span>
                </label>
              </div>
              <div
                class="timeline-wrapper"
              >
                <svg
                  height="150"
                  id="timeline"
                  style="min-width: 300px; min-height: 150px;"
                  viewBox="0 0 300 150"
                  width="300"
                >
                  <g
                    id="x-axis"
                  >
                    <g
                      fill="none"
                      id="x-axis__brush"
                      pointer-events="all"
                    >
                      <rect
                        class="overlay"
                        cursor="crosshair"
                        height="70"
                        pointer-events="all"
                        width="200"
                        x="50"
                        y="40"
                      />
                      <rect
                        class="selection"
                        cursor="move"
                        fill="#777"
                        fill-opacity="0.3"
                        shape-rendering="crispEdges"
                        stroke="#fff"
                        style="display: none;"
                      />
                      <rect
                        class="handle handle--w"
                        cursor="ew-resize"
                        style="display: none;"
                      />
                      <rect
                        class="handle handle--e"
                        cursor="ew-resize"
                        style="display: none;"
                      />
                    </g>
                    <g
                      fill="none"
                      font-family="sans-serif"
                      font-size="10"
                      id="x-axis__axis"
                      text-anchor="middle"
                      transform="translate(0, 80)"
                    >
                      <path
                        class="domain"
                        d="M50.5,6V0.5H250.5V6"
                        stroke="currentColor"
                      />
                      <g
                        class="tick"
                        opacity="1"
                        transform="translate(70.44976829135715,0)"
                      >
                        <line
                          stroke="currentColor"
                          y2="6"
                        />
                        <text
                          dy="0.71em"
                          fill="currentColor"
                          y="9"
                        >
                          1860
                        </text>
                      </g>
                      <g
                        class="tick"
                        opacity="1"
                        transform="translate(92.18943241289548,0)"
                      >
                        <line
                          stroke="currentColor"
                          y2="6"
                        />
                        <text
                          dy="0.71em"
                          fill="currentColor"
                          y="9"
                        >
                          1880
     ...

      128 |     await waitFor(() => {
      129 |       const tooltip = screen.queryByRole('tooltip');
    > 130 |       expect(tooltip).not.toBeInTheDocument();
          |                           ^
      131 |     });
      132 |   });
      133 |

      at test/pages/timeline.page.test.tsx:130:27
      at runWithExpensiveErrorDiagnosticsDisabled (node_modules/@testing-library/dom/dist/config.js:50:12)
      at checkCallback (node_modules/@testing-library/dom/dist/wait-for.js:141:77)
      at checkRealTimersCallback (node_modules/@testing-library/dom/dist/wait-for.js:133:16)
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:516:19)
```

**Comment by mfranke93** [comment]
I cannot reproduce the problem. I ran the tests at least 10 times each, both on an existing mirror of the repo and on a fresh clone. Can you confirm that you are on the newest `dev` commit as well (`v0.1.0-37-g27b6075`)?

**Comment by samuelbeck** [comment]
I just tried running the test on 27b6075181dddfd027c7857de08765ffc55b75fa and it passes. However, when I run it on 09d07fa63e8c4900d032466e9f7768b5f660b722 (last commit on the feat/vq-redesign branch) it fails. 

I'm not sure why because neither the test nor the timeline component code was changed.

**Comment by mfranke93** [comment]
It runs just fine for me on https://github.com/InTaVia/web/commit/09d07fa63e8c4900d032466e9f7768b5f660b722 :thinking:

**Comment by mfranke93** [comment]
It might be a timing issue. The particular line in the test checks that the tooltips also disappears again when the item is no longer hovered. It uses the `waitFor` function, which repeats the content tests until they pass, but gives up at some point.

The MUI tooltips have an animation on appear and disappear. On disappear, they obviously stay in the DOM until the animation is finished, then are removed. It seems like on your machine, the `waitFor` function sometimes gives up before the tooltip removal animation is finished. Unfortunately, since the tests never fail on my end, I cannot really test or fix anything here.

**Comment by mfranke93** [comment]
I could run into the issue by setting the `waitFor` timeout very low (300ms, the default is 1s). Can you please try if this fixes the issue on your end:

``` patch
diff --git i/test/pages/timeline.page.test.tsx w/test/pages/timeline.page.test.tsx
index 37243b3..b083362 100644
--- i/test/pages/timeline.page.test.tsx
+++ w/test/pages/timeline.page.test.tsx
@@ -128,7 +128,7 @@ describe('TimelinePage', () => {
     await waitFor(() => {
       const tooltip = screen.queryByRole('tooltip');
       expect(tooltip).not.toBeInTheDocument();
-    });
+    }, { timeout: 3000 });
   });

   it('should show person relations in the tooltip', async () => {
```
